In [1]:
import os
print(os.getcwd())

C:\Users\EliteBook\Machine_Learning_Course\Untitled Folder

In [2]:
import pandas as pd
df = pd.read_csv("crypto-markets.csv")

In [3]:
os.getcwd()

'C:\\Users\\EliteBook\\Machine_Learning_Course\\Untitled Folder'

In [4]:
df.shape

(942297, 13)

In [5]:
df.head()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market,close_ratio,spread
0,bitcoin,BTC,Bitcoin,2013-04-28,1,135.30,135.98,132.10,134.21,0.0,1.488567e+09,0.5438,3.88
1,bitcoin,BTC,Bitcoin,2013-04-29,1,134.44,147.49,134.00,144.54,0.0,1.603769e+09,0.7813,13.49
2,bitcoin,BTC,Bitcoin,2013-04-30,1,144.00,146.93,134.05,139.00,0.0,1.542813e+09,0.3843,12.88
3,bitcoin,BTC,Bitcoin,2013-05-01,1,139.00,139.89,107.72,116.99,0.0,1.298955e+09,0.2882,32.17
4,bitcoin,BTC,Bitcoin,2013-05-02,1,116.38,125.60,92.28,105.21,0.0,1.168517e+09,0.3881,33.32

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 942297 entries, 0 to 942296
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   slug         942297 non-null  str
 1   symbol       942297 non-null  str
 2   name         942297 non-null  str
 3   date         942297 non-null  str
 4   ranknow      942297 non-null  int64
 5   open         942297 non-null  float64
 6   high         942297 non-null  float64
 7   low          942297 non-null  float64
 8   close        942297 non-null  float64
 9   volume       942297 non-null  float64
 10  market       942297 non-null  float64
 11  close_ratio  942297 non-null  float64
 12  spread       942297 non-null  float64
dtypes: float64(8), int64(1), str(4)
memory usage: 121.0 MB

In [7]:
df.columns

Index(['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market', 'close_ratio', 'spread'],
      dtype='str')

In [8]:
df.describe()

,ranknow,open,high,low,close,volume,market,close_ratio,spread
count,942297.000000,9.422970e+05,9.422970e+05,9.422970e+05,9.422970e+05,9.422970e+05,9.422970e+05,942297.000000,9.422970e+05
mean,1000.170608,3.483522e+02,4.085930e+02,2.962526e+02,3.461018e+02,8.720383e+06,1.725060e+08,0.459499,1.123400e+02
std,587.575283,1.318436e+04,1.616386e+04,1.092931e+04,1.309822e+04,1.839802e+08,3.575590e+09,0.326160,6.783713e+03
min,1.000000,2.500000e-09,3.200000e-09,2.500000e-10,2.000000e-10,0.000000e+00,0.000000e+00,-1.000000,0.000000e+00
25%,465.000000,2.321000e-03,2.628000e-03,2.044000e-03,2.314000e-03,1.750000e+02,2.958100e+04,0.162900,0.000000e+00
50%,1072.000000,2.398300e-02,2.680200e-02,2.143700e-02,2.389200e-02,4.278000e+03,5.227960e+05,0.432400,0.000000e+00
75%,1484.000000,2.268600e-01,2.508940e-01,2.043910e-01,2.259340e-01,1.190900e+05,6.874647e+06,0.745800,3.000000e-02
max,2072.000000,2.298390e+06,2.926100e+06,2.030590e+06,2.300740e+06,2.384090e+10,3.265025e+11,1.000000,1.770563e+06

In [9]:
df.shape
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 942297 entries, 0 to 942296
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   slug         942297 non-null  str
 1   symbol       942297 non-null  str
 2   name         942297 non-null  str
 3   date         942297 non-null  str
 4   ranknow      942297 non-null  int64
 5   open         942297 non-null  float64
 6   high         942297 non-null  float64
 7   low          942297 non-null  float64
 8   close        942297 non-null  float64
 9   volume       942297 non-null  float64
 10  market       942297 non-null  float64
 11  close_ratio  942297 non-null  float64
 12  spread       942297 non-null  float64
dtypes: float64(8), int64(1), str(4)
memory usage: 121.0 MB

In [10]:
df.shape

(942297, 13)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 942297 entries, 0 to 942296
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   slug         942297 non-null  str
 1   symbol       942297 non-null  str
 2   name         942297 non-null  str
 3   date         942297 non-null  str
 4   ranknow      942297 non-null  int64
 5   open         942297 non-null  float64
 6   high         942297 non-null  float64
 7   low          942297 non-null  float64
 8   close        942297 non-null  float64
 9   volume       942297 non-null  float64
 10  market       942297 non-null  float64
 11  close_ratio  942297 non-null  float64
 12  spread       942297 non-null  float64
dtypes: float64(8), int64(1), str(4)
memory usage: 121.0 MB

In [12]:
df.describe()

,ranknow,open,high,low,close,volume,market,close_ratio,spread
count,942297.000000,9.422970e+05,9.422970e+05,9.422970e+05,9.422970e+05,9.422970e+05,9.422970e+05,942297.000000,9.422970e+05
mean,1000.170608,3.483522e+02,4.085930e+02,2.962526e+02,3.461018e+02,8.720383e+06,1.725060e+08,0.459499,1.123400e+02
std,587.575283,1.318436e+04,1.616386e+04,1.092931e+04,1.309822e+04,1.839802e+08,3.575590e+09,0.326160,6.783713e+03
min,1.000000,2.500000e-09,3.200000e-09,2.500000e-10,2.000000e-10,0.000000e+00,0.000000e+00,-1.000000,0.000000e+00
25%,465.000000,2.321000e-03,2.628000e-03,2.044000e-03,2.314000e-03,1.750000e+02,2.958100e+04,0.162900,0.000000e+00
50%,1072.000000,2.398300e-02,2.680200e-02,2.143700e-02,2.389200e-02,4.278000e+03,5.227960e+05,0.432400,0.000000e+00
75%,1484.000000,2.268600e-01,2.508940e-01,2.043910e-01,2.259340e-01,1.190900e+05,6.874647e+06,0.745800,3.000000e-02
max,2072.000000,2.298390e+06,2.926100e+06,2.030590e+06,2.300740e+06,2.384090e+10,3.265025e+11,1.000000,1.770563e+06

In [13]:
df["name"].unique()

<ArrowStringArray>
[           'Bitcoin',                'XRP',           'Ethereum',
            'Stellar',       'Bitcoin Cash',                'EOS',
           'Litecoin',             'Tether',         'Bitcoin SV',
            'Cardano',
 ...
   'PlayCoin [ERC20]',       'Dragon Token',            'OBXcoin',
               'APOT',        'Bgogo Token', 'UniversalRoyalCoin',
   'EtherDelta Token',            '42-coin',              'Bit20',
          'Project-X']
Length: 2071, dtype: str

In [14]:
df["name"].nunique()

2071

In [15]:
bitcoin = df[df["name"]== "bitcoin"]

In [16]:
bitcoin.head()

Empty DataFrame
Columns: [slug, symbol, name, date, ranknow, open, high, low, close, volume, market, close_ratio, spread]
Index: []

In [17]:
bitcoin.shape

(0, 13)

In [18]:
bitcoin.head()

Empty DataFrame
Columns: [slug, symbol, name, date, ranknow, open, high, low, close, volume, market, close_ratio, spread]
Index: []

In [19]:
bitcoin.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   slug         0 non-null      str
 1   symbol       0 non-null      str
 2   name         0 non-null      str
 3   date         0 non-null      str
 4   ranknow      0 non-null      int64
 5   open         0 non-null      float64
 6   high         0 non-null      float64
 7   low          0 non-null      float64
 8   close        0 non-null      float64
 9   volume       0 non-null      float64
 10  market       0 non-null      float64
 11  close_ratio  0 non-null      float64
 12  spread       0 non-null      float64
dtypes: float64(8), int64(1), str(4)
memory usage: 132.0 bytes

In [20]:
bitcoin.describe()

       ranknow  open  high  low  close  volume  market  close_ratio  spread
count      0.0   0.0   0.0  0.0    0.0     0.0     0.0          0.0     0.0
mean       NaN   NaN   NaN  NaN    NaN     NaN     NaN          NaN     NaN
std        NaN   NaN   NaN  NaN    NaN     NaN     NaN          NaN     NaN
min        NaN   NaN   NaN  NaN    NaN     NaN     NaN          NaN     NaN
25%        NaN   NaN   NaN  NaN    NaN     NaN     NaN          NaN     NaN
50%        NaN   NaN   NaN  NaN    NaN     NaN     NaN          NaN     NaN
75%        NaN   NaN   NaN  NaN    NaN     NaN     NaN          NaN     NaN
max        NaN   NaN   NaN  NaN    NaN     NaN     NaN          NaN     NaN

In [ ]:
df.info()

In [21]:
bitcoin = df[df["name"] -- "Bitcoin"]

TypeError: bad operand type for unary -: 'str'

In [22]:
bitcoin = df[df["name"] == "Bitcoin"]

In [23]:
bitcoin.info()

<class 'pandas.DataFrame'>
RangeIndex: 2042 entries, 0 to 2041
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   slug         2042 non-null   str
 1   symbol       2042 non-null   str
 2   name         2042 non-null   str
 3   date         2042 non-null   str
 4   ranknow      2042 non-null   int64
 5   open         2042 non-null   float64
 6   high         2042 non-null   float64
 7   low          2042 non-null   float64
 8   close        2042 non-null   float64
 9   volume       2042 non-null   float64
 10  market       2042 non-null   float64
 11  close_ratio  2042 non-null   float64
 12  spread       2042 non-null   float64
dtypes: float64(8), int64(1), str(4)
memory usage: 262.4 KB

In [24]:
bitcoin = df[df["name"] == "bitcoin"].copy()

In [25]:
bitcoin["date"] = pd.to_datetime(bitcoin["date"])

In [35]:
bitcoin.info()

<class 'pandas.DataFrame'>
RangeIndex: 2042 entries, 0 to 2041
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   slug         2042 non-null   str
 1   symbol       2042 non-null   str
 2   name         2042 non-null   str
 3   date         2042 non-null   datetime64[us]
 4   ranknow      2042 non-null   int64
 5   open         2042 non-null   float64
 6   high         2042 non-null   float64
 7   low          2042 non-null   float64
 8   close        2042 non-null   float64
 9   volume       2042 non-null   float64
 10  market       2042 non-null   float64
 11  close_ratio  2042 non-null   float64
 12  spread       2042 non-null   float64
dtypes: datetime64[us](1), float64(8), int64(1), str(3)
memory usage: 242.2 KB

In [27]:
bitcoin["date"].min()

NaT

In [28]:
bitcoin["date"].head(10)

Series([], Name: date, dtype: datetime64[s])

In [29]:
bitcoin["date"].iloc[0]

IndexError: single positional indexer is out-of-bounds

In [30]:
bitcoin = df[df["name"] == "Bitcoin"].copy()

In [31]:
bitcoin.shape

(2042, 13)

In [32]:
bitcoin["date"].head()

0    2013-04-28
1    2013-04-29
2    2013-04-30
3    2013-05-01
4    2013-05-02
Name: date, dtype: str

In [34]:
bitcoin["date"] = pd.to_datetime(bitcoin["date"])

In [36]:
bitcoin.info()

<class 'pandas.DataFrame'>
RangeIndex: 2042 entries, 0 to 2041
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   slug         2042 non-null   str
 1   symbol       2042 non-null   str
 2   name         2042 non-null   str
 3   date         2042 non-null   datetime64[us]
 4   ranknow      2042 non-null   int64
 5   open         2042 non-null   float64
 6   high         2042 non-null   float64
 7   low          2042 non-null   float64
 8   close        2042 non-null   float64
 9   volume       2042 non-null   float64
 10  market       2042 non-null   float64
 11  close_ratio  2042 non-null   float64
 12  spread       2042 non-null   float64
dtypes: datetime64[us](1), float64(8), int64(1), str(3)
memory usage: 242.2 KB

In [1]:
bitcoin

NameError: name 'bitcoin' is not defined

In [2]:
bitcoin["date"].max()

NameError: name 'bitcoin' is not defined

In [3]:
bitcoin["date"].min()

NameError: name 'bitcoin' is not defined

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("crypto-markets.csv")

In [6]:
bitcoin = df[df["name"] == "Bitcoin"].copy()

In [7]:
bitcoin["date"] = pd.to_datetime(bitcoin["date"])

In [8]:
bitcoin["date"].min()

Timestamp('2013-04-28 00:00:00')

In [9]:
bitcoin = df[df["name"] == "Bitcoin"].copy()